export {
  STAGE_WIDTH_M,
  STAGE_DEPTH_M,
  METERS_PER_COUNT,
  COUNTS_PER_FOUR_EIGHT_BLOCK,
  EIGHTS_PER_BLOCK,
} from "./types";
export type {
  Position,
  Performer,
  Formation,
  ChangeTier,
  ChangePoint,
  SectionType,
  Template,
  EightGridEntry,
  SongAnalysisResult,
  GeneratedCue,
  GenerateFormationsResult,
} from "./types";
export {
  TEMPLATES_25P,
  templatesForTier,
  resamplePositions,
  mirrorTemplate,
} from "./templates_25p";
export { generateAppFormationsFromChangePoints } from "./appBridge";
export {
  assignPerformers,
  assignPerformersOrdered,
  totalTravelMeters,
  maxTravelMeters,
} from "./assignment";
export {
  generateFormations,
  pickFormationPushingLimit,
  availableCountsBetween,
  availableCountsForFourEightBlock,
  computeMaxFeasibleDistance,
  songPhaseAt,
  moodFromSection,
  sectionAt,
  resolveSectionType,
  snapEightIndexToBlock,
} from "./formation_generator";
export { buildRealisticLayouts } from "./layouts_realistic";
export {
  selectChangePointsForCueCount,
  suggestedCueCountForDuration,
  clampTargetCueCount,
  AI_SUGGEST_CUE_PRESETS,
  AI_SUGGEST_CUE_MIN,
  AI_SUGGEST_CUE_MAX,
} from "./selectChangePoints";
export * from "./tier1";
export * as lightingSync from "./lightingSync";
export {
  generateLightingSyncSuggestion,
  lightingSyncPayloadToApp,
  CLASS_PROFILE_PRESETS,
  CLASS_TODDLER,
  CLASS_ADVANCED_MON7,
  CLASS_ELEMENTARY,
  getClassProfile,
  corpusSummary,
  LIGHTING_PLAN_SHOWS,
  suggestClassProfileId,
} from "./lightingSync";
export * as musicEngine from "./engine";
export {
  analyzeAudio,
  calculateRms,
  calculateSpectralFlux,
  calculateSpectralCentroid,
  calculateFrequencyBandEnergy,
  calculateEnergyCurve,
  detectBeats,
  detectOnsets,
  decodeAudio,
  DEFAULT_ANALYSIS_CONFIG,
  ANALYSIS_VERSION,
  analyzeMusicStructure,
  detectSections,
  detectPhrases,
  detectChangePoints,
  classifyHits,
  STRUCTURE_ANALYSIS_VERSION,
  DEFAULT_MUSIC_STRUCTURE_CONFIG,
  generateFormationCues,
  CUE_ANALYSIS_VERSION,
  DEFAULT_CUE_ENGINE_CONFIG,
  generateFormationCandidates,
  FORMATION_CANDIDATE_VERSION,
  defaultFormationTemplateRegistry,
  FormationTemplateRegistry,
  analyzeFormationTransition,
  analyzeFormationTransitions,
  calculateTravelDistance,
  calculateRequiredTravelTime,
  calculateMovementFeasibility,
  detectFormationCollisions,
  detectMovementCollisions,
  calculateTransitionScore,
  assignDancersToTargets,
  calculatePushingLimit,
  MOVEMENT_ANALYSIS_VERSION,
  scoreFormationCandidate,
  scoreFormationSequence,
  optimizeFormationSequence,
  FORMATION_SEQUENCE_VERSION,
  runBenchmark,
  evaluateSong,
  evaluateCues,
  evaluateSections,
  evaluateFormations,
  evaluateTransitions,
  evaluateSequence,
  calculateBenchmarkSummary,
  detectRegression,
  EVALUATION_VERSION,
  REALWORLD_VERSION,
  runRealWorldBenchmark,
  generateTuningCandidates,
  evaluateTuningCandidate,
  compareBenchmarkRuns,
  calculateHumanCeiling,
  calculateHumanCeilingRatio,
  generateFailureMatrix,
  generateTuningRecommendations,
  adviseImprovement,
  formatQualityReport,
  ADVISOR_VERSION,
  createAnnotationSession,
  validateAnnotationSession,
  calculateAnnotationQuality,
  calculateInterRaterAgreement,
  generateConsensus,
  generateGroundTruthSet,
  generateConsensusReviewItems,
  runCalibration,
  ANNOTATION_WORKFLOW_VERSION,
  runRealSongPilot,
  generatePilotReport,
  generateDisagreementHeatmap,
  generateLayerDiagnostics,
  PILOT_VERSION,
} from "./engine";
export type {
  AudioFeatureFrame,
  BeatEvent,
  TempoAnalysis,
  EnergyPoint,
  EnergyCurve,
  HitEvent,
  MusicAnalysisResultPhase1,
  AudioAnalysisConfig,
  MusicSection,
  MusicSectionType,
  MusicPhrase,
  MusicPhraseType,
  MusicChangePoint,
  ChangePointType,
  EventCluster,
  MusicStructureAnalysisResult,
  MusicStructureConfig,
  FormationCue,
  FormationCueIntent,
  CueAnalysisResult,
  CueEngineConfig,
  FormationRequest,
  FormationCueAction,
  FormationChangeMagnitude,
  EngineFormation,
  FormationType,
  FormationCandidate,
  FormationTemplate,
  MovementAbility,
  MovementTiming,
  DancerMovement,
  CollisionResult,
  MovementPlan,
  TransitionContext,
  TransitionAnalysis,
  CandidateScore,
  FormationSequenceScore,
  BeamSearchConfig,
  FormationOptimizationInput,
  FormationSequenceResult,
  EvaluationResult,
  BenchmarkSummary,
  BenchmarkConfig,
  RealWorldBenchmarkResult,
  TuningCandidate,
  QualityAdvisorReport,
  AnnotationSession,
  GroundTruthSet,
  RealWorldPilotResult,
} from "./engine";
