import type { RealWorldBenchmarkResult } from "../types/RealWorldTypes";

export function formatRealWorldReport(result: RealWorldBenchmarkResult): string {
  const pct = (v: number) => `${(v * 100).toFixed(1)}%`;
  const s = result.summary;
  return [
    "=====================================",
    "ChoreoCore Real World Benchmark",
    "===============================",
    "",
    `Songs: ${result.songsEvaluated}`,
    `Human Annotators: ${result.annotatorCount}`,
    `Human-Human Agreement: ${pct(result.humanHumanAgreement)}`,
    `AI-Human Agreement: ${pct(result.aiHumanAgreement)}`,
    `Human Ceiling Ratio: ${result.humanCeilingRatio.overall.toFixed(3)}`,
    "",
    `Overall: ${result.overall.toFixed(1)}`,
    `Grade: ${result.grade}`,
    `Status: ${result.status}`,
    "",
    "---",
    "",
    `Cue F1: ${pct(s.cueF1)}`,
    `Major Cue Recall: ${pct(s.majorCueRecall)}`,
    `Section Boundary: ${result.layerScores.phase2Structure.toFixed(1)}`,
    `Formation Top3: ${pct(s.formationTop3)}`,
    `Transition Correlation: ${s.transitionCorrelation.toFixed(2)}`,
    `Sequence Correlation: ${s.sequenceCorrelation.toFixed(2)}`,
    `Unsafe: ${pct(s.unsafeRecommendationRate)}`,
    "",
    "---",
    "",
    `Weakest: ${result.weakestBucket}`,
    `Strongest: ${result.strongestBucket}`,
    `Weakest Layer: ${result.weakestLayer}`,
    `Strongest Layer: ${result.strongestLayer}`,
    "",
    "Layer scores:",
    `  Phase 1 Audio: ${result.layerScores.phase1Audio.toFixed(1)}`,
    `  Phase 2 Structure: ${result.layerScores.phase2Structure.toFixed(1)}`,
    `  Phase 3 Cue: ${result.layerScores.phase3Cue.toFixed(1)}`,
    `  Phase 4 Formation: ${result.layerScores.phase4Formation.toFixed(1)}`,
    `  Phase 5 Movement: ${result.layerScores.phase5Movement.toFixed(1)}`,
    `  Phase 6 Sequence: ${result.layerScores.phase6Sequence.toFixed(1)}`,
    "",
    "Recommendations:",
    ...result.recommendations.map((r) => `  ${r.rank}. ${r.title} — ${r.detail}`),
    "",
    "=====================================",
  ].join("\n");
}
